version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - chroma_data:/app/chroma_data  # Persistent ChromaDB storage
    environment:
      - CHUNK_SIZE=512
      - CHUNK_OVERLAP=10
      - MAX_FILE_SIZE_MB=5
      - MAX_TEXT_LENGTH=50000
      - MAX_PDF_PAGES=20
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  chroma_data:  # Named volume for ChromaDB persistence 
  mongo_data:   # Named volume for MongoDB persistence 